version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/generators/app/templates/copy/'
    schedule:
      interval: daily
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'