version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    target-branch: 'v2'
  - package-ecosystem: npm
    directory: '/generators/app/templates/copy/'
    schedule:
      interval: weekly
    target-branch: 'v2'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
